# Generated by Django 3.2 on 2021-04-30 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Corp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DAT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Exclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('first_last_name', models.CharField(max_length=30)),
                ('second_last_name', models.CharField(max_length=30)),
                ('dni', models.CharField(max_length=10)),
                ('l_inte', models.BooleanField()),
                ('language_test', models.BooleanField()),
                ('admitted', models.BooleanField()),
                ('access', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='readPdfs.access')),
                ('corp', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='readPdfs.corp')),
                ('dat', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='readPdfs.dat')),
                ('exclusion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='readPdfs.exclusion')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='readPdfs.specialty')),
            ],
        ),
    ]
