# Generated by Django 3.2 on 2021-05-01 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readPdfs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teachers',
            new_name='Teacher',
        ),
        migrations.RemoveField(
            model_name='access',
            name='name',
        ),
    ]
