# Generated by Django 3.2 on 2021-05-01 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readPdfs', '0002_auto_20210501_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='l_inte',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='language_test',
            field=models.CharField(max_length=10),
        ),
    ]
