# Generated by Django 3.2 on 2021-05-01 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readPdfs', '0005_auto_20210501_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access',
            name='code',
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='corp',
            name='code',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='corp',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='dat',
            name='name',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='exclusion',
            name='code',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='exclusion',
            name='name',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
