# Generated by Django 3.2 on 2021-05-01 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('readPdfs', '0006_auto_20210501_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='access',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='readPdfs.access'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='corp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='readPdfs.corp'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='dat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='readPdfs.dat'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='specialty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='readPdfs.specialty'),
        ),
    ]
