# Generated by Django 3.2 on 2021-05-01 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readPdfs', '0007_auto_20210501_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='dni',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='first_last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='second_last_name',
            field=models.CharField(max_length=50),
        ),
    ]
