# Generated by Django 3.2 on 2021-05-01 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readPdfs', '0008_auto_20210501_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialty',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
