# Generated by Django 3.2 on 2021-05-01 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readPdfs', '0009_alter_specialty_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialty',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
